
["Configs for Kendrome VH Tweaks"]
	#Should tooltips be compact (less spaces, etc)
	"Enable compact mode" = true
	#Shows relative values for jewel affixs in tooltips
	"Enable jewel relative tooltips" = true
	#Show a rating instead of the relative value in jewel tooltips
	"Enable jewel rating tooltips" = false
	#Require key to show (None for always show)
	#Allowed Values: None, Shift, Alt, Ctrl
	"Jewel relative tooltips key" = "None"
	#Show gear comparison tooltips
	"Enable gear comparison tooltips" = true
	#Require key to show (None for always show)
	#Allowed Values: None, Shift, Alt, Ctrl
	"Gear Comparison tooltips key" = "None"

