
["Gameplay Settings"]
	#Controls whether Mote of Purity, Sanctity, and Clarity should work in the Crystal Workbench. (default: false)
	enableMoteRecipes = false
	#The max capacity that can be added to a tool with Resonating Reinforcements. (default: 20)
	resonatingReinforcementMaxCapacityAdded = 20
	#Controls whether or not wandering wisps should spawn (default: true)
	disableWanderingWispSpawning = true
	#How much a difference in levels should be allowed for Soul Flames before not raising stacks (default: 3)
	soulFlameLevelAllowance = 3

["Developer Settings"]
	#Don't recommend turning on unless asked, enables debug messages for development. (default: false)
	enableDebugMode = false

