
["Vault Settings"]
	#Controls whether Creative flight should be blocked while inside a vault. (default: true)
	disableFlightInVaults = true

["Gameplay Settings"]
	#Controls whether Mote of Purity, Sanctity, and Clarity should work in the Crystal Workbench. (default: false)
	enableMoteRecipes = false

["Compatability Settings"]

	["Compatability Settings"."Item Borders"]
		#Whether Item Borders from the Item Borders mod should show in terminals like Refined Storage, AE2, etc., this will also cause them to show on the hot-bar. (default: true)
		displayItemBordersInTerminals = true

["Developer Settings"]
	#Don't recommend turning on unless asked, enables debug messages for development. (default: false)
	enableDebugMode = false

